#!/usr/bin/env node
// この環境で実モデルを作るためのTensorFlow.js版。同じGPT構造をPyTorch版と共有する。
import * as tf from '@tensorflow/tfjs-node';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const args = Object.fromEntries(process.argv.slice(2).map((x,i,a)=>x.startsWith('--')?[x.slice(2),a[i+1]]:null).filter(Boolean));
const steps = +(args.steps || 2000), batchSize = +(args.batch || 12);
const config = {context_length:64, embedding_dim:80, layers:4, attention_heads:4, ff_multiplier:4, vocab_limit:1600, architecture:'character-gpt', format:'milli-tfjs-flat-v1'};
const corpus = fs.readFileSync(path.join(root,'data/corpus.txt'),'utf8');
const counts = new Map(); for(const c of corpus) counts.set(c,(counts.get(c)||0)+1);
const specials=['<PAD>','<UNK>']; const chars=[...counts.entries()].sort((a,b)=>b[1]-a[1]).slice(0,config.vocab_limit-specials.length).map(x=>x[0]);
const itos=[...specials,...chars], stoi=new Map(itos.map((c,i)=>[c,i])); config.vocab_size=itos.length;
const ids=Int32Array.from([...corpus].map(c=>stoi.get(c)??1));
const split=Math.floor(ids.length*.96), train=ids.subarray(0,split), val=ids.subarray(split);
const vars={}, desc=[]; function variable(name,shape,scale=.02,zeros=false,ones=false){let t=zeros?tf.zeros(shape):ones?tf.ones(shape):tf.randomNormal(shape,0,scale);const v=tf.variable(t,true,name);vars[name]=v;desc.push({name,shape,length:shape.reduce((a,b)=>a*b,1)});return v}
const d=config.embedding_dim,H=config.attention_heads,hd=d/H;
variable('token_embedding',[config.vocab_size,d]); variable('position_embedding',[config.context_length,d]); variable('lm_head',[d,config.vocab_size]); variable('lm_bias',[config.vocab_size],.02,true);
for(let l=0;l<config.layers;l++){for(const n of ['ln1_gamma','ln2_gamma'])variable(`b${l}_${n}`,[d],.02,false,true);for(const n of ['ln1_beta','ln2_beta'])variable(`b${l}_${n}`,[d],.02,true);variable(`b${l}_qkv_w`,[d,3*d]);variable(`b${l}_qkv_b`,[3*d],.02,true);variable(`b${l}_proj_w`,[d,d]);variable(`b${l}_proj_b`,[d],.02,true);variable(`b${l}_fc1_w`,[d,4*d]);variable(`b${l}_fc1_b`,[4*d],.02,true);variable(`b${l}_fc2_w`,[4*d,d]);variable(`b${l}_fc2_b`,[d],.02,true)}
const paramCount=desc.reduce((s,x)=>s+x.length,0); console.log({characters:ids.length,vocab:itos.length,paramCount});
function ln(x,g,b){const {mean,variance}=tf.moments(x,-1,true);return x.sub(mean).mul(tf.rsqrt(variance.add(1e-5))).mul(g).add(b)}
function dense(x,w,b){const lead=x.shape.slice(0,-1),out=w.shape[1];return x.reshape([-1,x.shape.at(-1)]).matMul(w).add(b).reshape([...lead,out])}
function forward(idx){return tf.tidy(()=>{const B=idx.shape[0],T=idx.shape[1];let x=tf.gather(vars.token_embedding,idx).add(tf.gather(vars.position_embedding,tf.range(0,T,1,'int32')));for(let l=0;l<config.layers;l++){let n=ln(x,vars[`b${l}_ln1_gamma`],vars[`b${l}_ln1_beta`]);let qkv=dense(n,vars[`b${l}_qkv_w`],vars[`b${l}_qkv_b`]).reshape([B,T,3,H,hd]).transpose([2,0,3,1,4]);let [q,k,v]=tf.unstack(qkv);let scores=q.matMul(k,false,true).div(Math.sqrt(hd));const mask=tf.linalg.bandPart(tf.ones([T,T]),-1,0);scores=scores.add(tf.onesLike(mask).sub(mask).mul(-1e9));let att=tf.softmax(scores,-1).matMul(v).transpose([0,2,1,3]).reshape([B,T,d]);att=dense(att,vars[`b${l}_proj_w`],vars[`b${l}_proj_b`]);x=x.add(att);n=ln(x,vars[`b${l}_ln2_gamma`],vars[`b${l}_ln2_beta`]);let h=dense(n,vars[`b${l}_fc1_w`],vars[`b${l}_fc1_b`]);h=tf.mul(.5,h).mul(tf.add(1,tf.erf(h.div(Math.sqrt(2)))));x=x.add(dense(h,vars[`b${l}_fc2_w`],vars[`b${l}_fc2_b`]));}x=ln(x,tf.ones([d]),tf.zeros([d]));return dense(x,vars.lm_head,vars.lm_bias)})}
function batch(data){const x=new Int32Array(batchSize*config.context_length),y=new Int32Array(x.length);for(let b=0;b<batchSize;b++){const s=Math.floor(Math.random()*(data.length-config.context_length-1));for(let t=0;t<config.context_length;t++){x[b*config.context_length+t]=data[s+t];y[b*config.context_length+t]=data[s+t+1]}}return [tf.tensor2d(x,[batchSize,config.context_length],'int32'),tf.tensor1d(y,'int32')]}
const opt=tf.train.adam(3e-4); let lastLoss=0; const started=Date.now();
function languageLoss(y,logits){return tf.losses.softmaxCrossEntropy(tf.oneHot(y,config.vocab_size),logits).mean()}
async function lossOn(data){const [x,y]=batch(data);const value=tf.tidy(()=>languageLoss(y,forward(x).reshape([-1,config.vocab_size])));const n=(await value.data())[0];x.dispose();y.dispose();value.dispose();return n}
function save(step,trainLoss,valLoss){const buffers=[];let offset=0;for(const item of desc){const arr=vars[item.name].dataSync();buffers.push(Buffer.from(arr.buffer,arr.byteOffset,arr.byteLength));item.offset=offset;offset+=arr.length*4}fs.writeFileSync(path.join(root,'model',`model-${step}.weights.bin`),Buffer.concat(buffers));const td=JSON.parse(fs.readFileSync(path.join(root,'data/training_data.json')));const meta={...config,parameters:paramCount,training_steps:step,training_texts:td.meta.persona_pairs+td.meta.unique_texts,persona_training_pairs:td.meta.persona_pairs,source_rows:td.meta.source_rows,total_characters:[...corpus].length,training_loss:+trainLoss.toFixed(4),validation_loss:+valLoss.toFixed(4),trained_at:new Date().toISOString(),weights_file:`model-${step}.weights.bin`,weights:desc};fs.writeFileSync(path.join(root,'model',`training_meta-${step}.json`),JSON.stringify(meta,null,2));if(step===steps){fs.copyFileSync(path.join(root,'model',`model-${step}.weights.bin`),path.join(root,'model','model.weights.bin'));fs.writeFileSync(path.join(root,'model','training_meta.json'),JSON.stringify({...meta,weights_file:'model.weights.bin'},null,2));fs.writeFileSync(path.join(root,'model','config.json'),JSON.stringify(config,null,2));fs.writeFileSync(path.join(root,'model','vocab.json'),JSON.stringify({itos,stoi:Object.fromEntries(stoi)},null,2));}}
for(let step=1;step<=steps;step++){const [x,y]=batch(train);const loss=opt.minimize(()=>tf.tidy(()=>languageLoss(y,forward(x).reshape([-1,config.vocab_size]))),true);lastLoss=(await loss.data())[0];x.dispose();y.dispose();loss.dispose();if(step%50===0)console.log(`step ${step}/${steps} loss ${lastLoss.toFixed(4)} ${((Date.now()-started)/1000).toFixed(0)}s`);if([500,2000,5000].includes(step)||step===steps){const vl=await lossOn(val);save(step,lastLoss,vl);console.log(`saved ${step}, val ${vl.toFixed(4)}`)}await tf.nextFrame()}
